# Generated by Django 4.0.6 on 2022-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, default='default/mediaDefaultImage.jpg', upload_to='media/storie_image'),
        ),
    ]
