# Generated by Django 4.0.6 on 2022-08-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_savedstories_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(related_name='stories', through='blog.StoryTag', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='tagfollower',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_follower', to='blog.tag'),
        ),
    ]
