# Generated by Django 4.0.6 on 2022-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_photo',
            field=models.ImageField(blank=True, upload_to='about_photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='profile_photo'),
        ),
    ]
